// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE3pVzR-aTF8yRHjpEOonK6HSux-XFr4M',
    appId: '1:301420763380:web:436bfc3e6b08ba59f266a1',
    messagingSenderId: '301420763380',
    projectId: 'maangengineer',
    authDomain: 'maangengineer.firebaseapp.com',
    storageBucket: 'maangengineer.appspot.com',
    measurementId: 'G-RJ93X16YSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKC6Sq52Uwag3PY1-M73xAG8Pydi3Sw30',
    appId: '1:301420763380:android:686cfc204a2a603ef266a1',
    messagingSenderId: '301420763380',
    projectId: 'maangengineer',
    storageBucket: 'maangengineer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArri6xHzMZbZk_9A-lcnDcUpo-ZdgjwOc',
    appId: '1:301420763380:ios:838f74589ab8b9aff266a1',
    messagingSenderId: '301420763380',
    projectId: 'maangengineer',
    storageBucket: 'maangengineer.appspot.com',
    iosClientId: '301420763380-jj476l3rrmo450nfd443vti184j9vjnh.apps.googleusercontent.com',
    iosBundleId: 'com.aditythakur.maangengineer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArri6xHzMZbZk_9A-lcnDcUpo-ZdgjwOc',
    appId: '1:301420763380:ios:1d9516a43f27e3f1f266a1',
    messagingSenderId: '301420763380',
    projectId: 'maangengineer',
    storageBucket: 'maangengineer.appspot.com',
    iosClientId: '301420763380-7fg0qa4h73qobmu6svgjnja53h84vi96.apps.googleusercontent.com',
    iosBundleId: 'com.aditythakur.maangengineer.RunnerTests',
  );
}
